import { pixiVersion, version } from './version';
// https://www.asciiart.eu/image-to-ascii
const ascii = `     ........        .....     ............    ............. ...........     
  .............     .......   ................ ............. ..............  
 ..............    .........   ............... ............. ..............  
 .....            ...........   .............. ............  ..............  
 .....           ...... ......  .............. ............. .............   
 .............. ......   .....  ............   ............. .....  ......   
  ...................     ..... .....          ............. .....   ....... 
    ................       ..........          ............. .....     ..... `;

export function sayHello() {
  const hello = `\n${ascii}\n\n v${version} | %cPixi.js v${pixiVersion} %c| %chttps://github.com/anthonysapp/caper\n\n`;
  console.log(
    hello,
    'color: #E91E63; font-weight: 600;',
    'color: inherit;',
    'color: #00BCD4; text-decoration: underline;',
  );
}
