
// This file is auto-generated by caper. Do not edit.
import type { dataSchema, actions, contexts } from '../../caper.config';
import type { KitchenSinkApplication } from '@/KitchenSinkApplication';
// Data
type AppData = typeof dataSchema;

// Action Contexts
type AppContexts = (typeof contexts)[number];

// Actions
type AppActionMap = typeof actions;
type AppActions = keyof AppActionMap;

// Scenes
type AppScenes = 
  | 'start'
  | 'focus'
  | 'voiceover'
  | 'audio'
  | 'music'
  | 'animated-sprites'
  | 'spine'
  | 'assets'
  | 'pause'
  | 'timer'
  | 'endless-runner'
  | 'crunch-physics'
  | 'rive'
  | 'firebase'
  | 'buttons'
  | 'flex-container'
  | 'ui-popup'
  | 'text'
  | 'ui-canvas'
  | 'ui-input'
  | 'ui-toaster';

// Plugins
type AppPlugins = 
  | 'crunch'
  | 'google-analytics'
  | 'rive'
  | 'rollbar'
  | 'firebase'
  | 'test';

// Popups
type AppPopups = 
  | 'example'
  | 'confirm';

// Entities
type AppEntities = 
  | 'actor'
  | 'boy'
  | 'dragon'
  | 'player';

// Locale keys (flattened dot-paths from src/locales/<reference>.ts)
type AppLocaleKeys = 
  | 'foo'
  | 'html'
  | 'obj.foo'
  | 'opts'
  | 'replace.replace'
  | 'replace.replaceOpts';

/**
 * Add type overrides to the framework
 */
declare module '@caper/core' {
  interface AppTypeOverrides {
    App: KitchenSinkApplication;
    Data: AppData;
    Contexts: AppContexts;
    Actions: AppActions;
    ActionMap: AppActionMap;
    Scenes: AppScenes;
    Plugins: AppPlugins;
    Popups: AppPopups;
    Entities: AppEntities;
    LocaleKeys: AppLocaleKeys;
    Eases: Eases;
  }
}
