
// This file is auto-generated by caper. Do not edit.
import type { initialData, actions, contexts } from '../../caper.config';
import type { App } from '@/App';
// Data
type AppData = typeof initialData;

// Action Contexts
type AppContexts = (typeof contexts)[number];

// Actions
type AppActionMap = typeof actions;
type AppActions = keyof AppActionMap;

// Scenes
type AppScenes = 
  | 'main';

// Plugins
type AppPlugins = string;

// Popups
type AppPopups = 
  | 'example';

// Entities
type AppEntities = 
  | 'marker';

// UI Elements
type AppUIs = 
  | 'badge';

// Class maps — typeof-import pointers to the real discovered classes. The
// framework uses these with ConstructorParameters<> + InstanceType<> + infer
// to derive typed props and return types for this.add.entity / popups.show /
// scenes.load without any AST type extraction.
type AppSceneClasses = {
  "main": typeof import('@/scenes/Main').default;
};

type AppPopupClasses = {
  "example": typeof import('@/popups/Example').default;
};

type AppEntityClasses = {
  "marker": typeof import('@/entities/Marker').default;
};

type AppUIClasses = {
  "badge": typeof import('@/ui/Badge').default;
};

// Locale keys (flattened dot-paths from src/locales/<reference>.ts)
type AppLocaleKeys = string;

/**
 * Add type overrides to the framework
 */
declare module '@caperjs/core' {
  interface AppTypeOverrides {
    App: App;
    Data: AppData;
    Contexts: AppContexts;
    Actions: AppActions;
    ActionMap: AppActionMap;
    Scenes: AppScenes;
    Plugins: AppPlugins;
    Popups: AppPopups;
    Entities: AppEntities;
    SceneClasses: AppSceneClasses;
    PopupClasses: AppPopupClasses;
    EntityClasses: AppEntityClasses;
    UIs: AppUIs;
    UIClasses: AppUIClasses;
    LocaleKeys: AppLocaleKeys;
    Eases: Eases;
  }
}
