import { bgRed, bold, cyan, green, white } from 'kleur/colors';

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * `caper agent init` — installs the shipped `caper` agent skill into the
 * current app and upserts a marker-delimited pointer block into the app's
 * agent context file (`AGENTS.md` or `CLAUDE.md`).
 */

const START_MARKER = '<!-- caper:agent-start -->';
const END_MARKER = '<!-- caper:agent-end -->';

// `.href` so this also works where the global URL is a DOM polyfill (vitest + happy-dom).
function resolveModuleRelative(rel) {
  return fileURLToPath(new URL(rel, import.meta.url).href);
}

function readVersion() {
  return JSON.parse(fs.readFileSync(resolveModuleRelative('../package.json'), 'utf-8')).version;
}

function makeBlock(skillPath, version) {
  return `${START_MARKER}
## Caper (engine) — agent pointers

This app runs on the Caper engine (\`@caperjs/core@${version}\`). Generated by \`caper agent init\`; re-run it after upgrading caper. Do not edit between these markers.

- Before engine-facing work (scenes, entities, popups, UI, plugins, \`caper.config.ts\`, assets, generated types), load the \`caper\` skill at \`${skillPath}\`.
- Read the reference by section, not whole: \`node_modules/@caperjs/core/extras/llms.txt\` (\`grep -n '^## '\` for the outline). Engine source ships at \`node_modules/@caperjs/core/src/\`.
- Verify: typecheck → build → drive the running app through \`window.Caper\` / \`Caper.automation[appId]\` (llms.txt §17). Never leave a dev server running in the foreground.
${END_MARKER}`;
}

function upsertContext(cwd, dir) {
  const candidates = ['AGENTS.md', 'CLAUDE.md'];
  let contextFile = candidates.find((name) => fs.existsSync(path.join(cwd, name)));

  if (!contextFile) {
    contextFile = 'AGENTS.md';
  }

  const contextPath = path.resolve(cwd, contextFile);
  const existing = fs.existsSync(contextPath) ? fs.readFileSync(contextPath, 'utf-8') : '';
  const skillPath = path.posix.join(dir, 'caper/SKILL.md');
  const version = readVersion();
  const block = makeBlock(skillPath, version);

  const startIndex = existing.indexOf(START_MARKER);
  const endIndex = existing.indexOf(END_MARKER);

  let contents;
  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const before = existing.slice(0, startIndex);
    const after = existing.slice(endIndex + END_MARKER.length);
    const trimmedBefore = before.replace(/\s+$/, '');
    const trimmedAfter = after.replace(/^\s+/, '');
    const spacerBefore = trimmedBefore ? '\n\n' : '';
    const spacerAfter = trimmedAfter ? '\n\n' : '';
    contents = `${trimmedBefore}${spacerBefore}${block}${spacerAfter}${trimmedAfter}`;
  } else if (existing) {
    const spacer = existing.endsWith('\n\n') ? '' : '\n\n';
    contents = `${existing.replace(/\s+$/, '')}${spacer}${block}\n`;
  } else {
    contents = `${block}\n`;
  }

  fs.writeFileSync(contextPath, contents, 'utf-8');
  return contextPath;
}

export async function agentInit(cwd, { dir = '.claude/skills' } = {}) {
  const skillSource = resolveModuleRelative('../extras/skills/caper/SKILL.md');
  const skillDir = path.resolve(cwd, dir, 'caper');
  const skillFile = path.join(skillDir, 'SKILL.md');

  fs.mkdirSync(skillDir, { recursive: true });
  fs.copyFileSync(skillSource, skillFile);

  const contextFile = upsertContext(cwd, dir);

  console.log(green(bold('✓ Created caper skill')) + ` ${cyan(path.relative(cwd, skillFile).replace(/\\/g, '/'))}`);
  console.log(green(bold('✓ Updated agent context')) + ` ${cyan(path.relative(cwd, contextFile).replace(/\\/g, '/'))}`);

  return { skillFile, contextFile };
}

export async function agent(args) {
  if (args[0] === 'init') {
    let dir = '.claude/skills';
    for (let i = 1; i < args.length; i++) {
      if (args[i] === '--dir' && args[i + 1]) {
        dir = args[i + 1];
        i++;
      }
    }
    await agentInit(process.cwd(), { dir });
    return;
  }

  const subcommand = args[0] ?? '(none)';
  console.error(bold(bgRed(white(`Unknown agent command: "${subcommand}". Please use "init".`))));
  process.exit(1);
}
